# Generated by Django 2.2.10 on 2020-11-07 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0002_auto_20201106_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 483305)),
        ),
        migrations.AlterField(
            model_name='careinstructions',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 501994)),
        ),
        migrations.AlterField(
            model_name='color',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 482022)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 513503)),
        ),
        migrations.AlterField(
            model_name='deliveryplaces',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 532100)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 487029)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 490192)),
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 500764)),
        ),
        migrations.AlterField(
            model_name='lookbookcategories',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 499537)),
        ),
        migrations.AlterField(
            model_name='measurement_master',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 537983)),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 484856)),
        ),
        migrations.AlterField(
            model_name='measures',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 539101)),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 541502)),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 502988)),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 503828)),
        ),
        migrations.AlterField(
            model_name='productuom',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 537022)),
        ),
        migrations.AlterField(
            model_name='recenltyviewedproducts',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 520165)),
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 526177)),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 486092)),
        ),
        migrations.AlterField(
            model_name='styles',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 489229)),
        ),
        migrations.AlterField(
            model_name='usercustommeasuresmaster',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 21, 23, 516507)),
        ),
    ]
