# Generated by Django 2.2.10 on 2020-11-07 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0003_auto_20201107_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 220845)),
        ),
        migrations.AlterField(
            model_name='careinstructions',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 239912)),
        ),
        migrations.AlterField(
            model_name='color',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 219687)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 251583)),
        ),
        migrations.AlterField(
            model_name='deliveryplaces',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 270011)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 224516)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 227537)),
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 238618)),
        ),
        migrations.AlterField(
            model_name='lookbookcategories',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 237020)),
        ),
        migrations.AlterField(
            model_name='measurement_master',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 276082)),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 222421)),
        ),
        migrations.AlterField(
            model_name='measures',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 277783)),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 280481)),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 241006)),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 241935)),
        ),
        migrations.AlterField(
            model_name='productuom',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 275173)),
        ),
        migrations.AlterField(
            model_name='recenltyviewedproducts',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 258058)),
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 264041)),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 223612)),
        ),
        migrations.AlterField(
            model_name='styles',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 226580)),
        ),
        migrations.AlterField(
            model_name='usercustommeasuresmaster',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 254540)),
        ),
    ]
