# Generated by Django 2.2.10 on 2020-12-30 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoitymoppet', '0010_auto_20201118_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.IntegerField()),
                ('shipping_charge', models.CharField(choices=[('courier_charges', 'Courier Charges')], default='courier_charges', max_length=255)),
                ('migrate_data', models.BooleanField(blank=True, default=False, null=True)),
                ('product_id', models.IntegerField()),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Product',
            },
        ),
        migrations.AddField(
            model_name='paymentreference',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 91953)),
        ),
        migrations.AlterField(
            model_name='careinstructions',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 121370)),
        ),
        migrations.AlterField(
            model_name='color',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 89962)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 138945)),
        ),
        migrations.AlterField(
            model_name='deliveryplaces',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 162290)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 98227)),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 103361)),
        ),
        migrations.AlterField(
            model_name='lookbook',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 119574)),
        ),
        migrations.AlterField(
            model_name='lookbookcategories',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 117696)),
        ),
        migrations.AlterField(
            model_name='measurement_master',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 168305)),
        ),
        migrations.AlterField(
            model_name='measurements',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 94597)),
        ),
        migrations.AlterField(
            model_name='measures',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 169679)),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 172691)),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 122904)),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 124200)),
        ),
        migrations.AlterField(
            model_name='productuom',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 128691)),
        ),
        migrations.AlterField(
            model_name='recenltyviewedproducts',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 147788)),
        ),
        migrations.AlterField(
            model_name='savedcard',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 155322)),
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 96628)),
        ),
        migrations.AlterField(
            model_name='styles',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 101603)),
        ),
        migrations.AlterField(
            model_name='usercustommeasuresmaster',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 30, 9, 9, 5, 143080)),
        ),
    ]
