# Generated by Django 2.2.10 on 2020-11-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 457828)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 402546)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 459077)),
        ),
        migrations.AlterField(
            model_name='country',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 393164)),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 385389)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 462593)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 466356)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 467418)),
        ),
        migrations.AlterField(
            model_name='homepageadvertise',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 455271)),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 453755)),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 456525)),
        ),
        migrations.AlterField(
            model_name='paymentoptions',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 469799)),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 461246)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 464035)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 468602)),
        ),
        migrations.AlterField(
            model_name='uiconfiguration',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 16, 40, 16, 470888)),
        ),
    ]
