# Generated by Django 2.2.10 on 2020-11-07 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_links', '0004_auto_20201107_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 145360)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 96983)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 146629)),
        ),
        migrations.AlterField(
            model_name='country',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 90718)),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 84001)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 149830)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 152406)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 153427)),
        ),
        migrations.AlterField(
            model_name='homepageadvertise',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 142723)),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 141331)),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 144106)),
        ),
        migrations.AlterField(
            model_name='paymentoptions',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 155783)),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 148607)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 151107)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 154581)),
        ),
        migrations.AlterField(
            model_name='uiconfiguration',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 8, 18, 23, 156868)),
        ),
    ]
