# Generated by Django 2.2.10 on 2020-11-12 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_links', '0007_auto_20201112_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 18337)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 35, 973133)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 19418)),
        ),
        migrations.AlterField(
            model_name='country',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 35, 967115)),
        ),
        migrations.AlterField(
            model_name='currencycode',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 35, 960932)),
        ),
        migrations.AlterField(
            model_name='disclaimer',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 22598)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 24877)),
        ),
        migrations.AlterField(
            model_name='faq',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 25830)),
        ),
        migrations.AlterField(
            model_name='homepageadvertise',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 15735)),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 14281)),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 17064)),
        ),
        migrations.AlterField(
            model_name='paymentoptions',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 27930)),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 21234)),
        ),
        migrations.AlterField(
            model_name='terms',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 23645)),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 26819)),
        ),
        migrations.AlterField(
            model_name='uiconfiguration',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 36, 28944)),
        ),
    ]
