# Generated by Django 2.2.10 on 2020-11-06 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('alternate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('default', models.BooleanField(default=False, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 13, 17, 36, 421834))),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('editable', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', max_length=20)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_birth_date', models.DateField()),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 13, 17, 36, 423043))),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('migrate_data', models.BooleanField(blank=True, default=False, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pancard_number', models.CharField(blank=True, max_length=255, null=True)),
                ('aadharcard_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aadharcard_number', models.CharField(blank=True, max_length=255, null=True)),
                ('user_contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('user_sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 6, 13, 17, 36, 416774))),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
