# Generated by Django 2.2.10 on 2020-11-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20201106_1317'),
        ('generic_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='generic_links.HoityCountry'),
        ),
        migrations.AddField(
            model_name='address',
            name='user_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='generic_links.HoityState'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
    ]
