# Generated by Django 2.2.10 on 2020-11-12 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201107_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 6, 17, 37, 481355)),
        ),
        migrations.AlterField(
            model_name='child',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 6, 17, 37, 482546)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 6, 17, 37, 476517)),
        ),
    ]
