# Generated by Django 2.2.10 on 2020-11-12 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201112_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 35, 858145)),
        ),
        migrations.AlterField(
            model_name='child',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 35, 859248)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 7, 20, 35, 853439)),
        ),
    ]
