# Generated by Django 2.2.10 on 2020-11-07 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_order', '0004_auto_20201107_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 268858)),
        ),
        migrations.AlterField(
            model_name='statusoption',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 271970)),
        ),
        migrations.AlterField(
            model_name='userqueries',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 7, 5, 44, 29, 274055)),
        ),
    ]
