# Generated by Django 2.2.10 on 2020-11-18 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry_order', '0010_auto_20201116_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 11, 57, 9, 246565)),
        ),
        migrations.AlterField(
            model_name='statusoption',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 11, 57, 9, 249401)),
        ),
        migrations.AlterField(
            model_name='userqueries',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 18, 11, 57, 9, 251246)),
        ),
        migrations.AlterField(
            model_name='userqueries',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Query Type'),
        ),
    ]
